---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hmc-operator-interaction
  namespace: flux-system
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          product.mirantis.com: hmc
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: hmc
    ports:
    - port: http
  podSelector:
    matchLabels:
      app: source-controller
  policyTypes:
  - Ingress
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: hmc
  namespace: hmc-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/mirantis/hmc/charts/hmc
  ref:
    tag: 0.0.4
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc
  namespace: hmc-system
spec:
  chartRef:
    kind: OCIRepository
    name: hmc
    namespace: hmc-system
  interval: 10m
  values:
    flux2:
      enabled: false
