---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: global-services
  namespace: hmc-system
spec:
  interval: 10m0s
  path: ./services
  prune: true
  sourceRef:
    kind: GitRepository
    name: hmc-fluxcd-monorepo
    namespace: hmc-system