---
apiVersion: v1
kind: Namespace
metadata:
  name: hmc-system
  labels:
    product.mirantis.com: hmc

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hmc-fluxcd-monorepo
  namespace: hmc-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Algeran/hmc-flux-standby.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hmc-system
  namespace: hmc-system
spec:
  interval: 10m0s
  path: ./management/hmc-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: hmc-fluxcd-monorepo