---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: hmc-system
spec:
  interval: 10m0s
  path: ./management/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: hmc-fluxcd-monorepo
    namespace: hmc-system