---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hmc-system
  namespace: hmc-system
spec:
  interval: 10m0s
  path: ./management/staging/hmc-system/components
  prune: true
  sourceRef:
    kind: GitRepository
    name: hmc-system

