---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: providers
  namespace: hmc-system
spec:
  interval: 10m0s
  path: ./providers/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: providers

