---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./management/staging/sealed-secrets/components
  prune: true
  sourceRef:
    kind: GitRepository
    name: sealed-secrets

