---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: azure-cluster-identity
  namespace: hmc-system
spec:
  allowedNamespaces: {}
  clientID: 314178d3-c7b0-4285-8f4b-21a257a5a45e
  clientSecret:
    name: azure-cluster-identity-secret
    namespace: hmc-system
  tenantID: 6d498697-2abe-46df-ae3e-4e5b2e25f280
  type: ServicePrincipal

---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: azure-credential
  namespace: hmc-system
spec:
  description: "Basic Azure credentials"
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: azure-cluster-identity
    namespace: hmc-system