---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-cluster-identity-secret
  namespace: hmc-system
spec:
  encryptedData:
    AccessKeyID: AgBjlSYbF5ZP8Yy7I85hFCPsGhp3IfuGWvICvH2mmuGAXUIcdgJlEPuz6lBX8mDrs0dFb5Fox9+dGaFK+C9AiUGfAQx8zBIhshcg+SgVvJNfXOzDYA7eJv4D2jFL/WeoCF13diqsRczCY6xz9PJ6XtTMKI2ByE82zKIYMDj1ihXaIH0ZML0xjfz3e6ZHs8OvgpRQyJFbvg+zZ4FOiWc9Yk/YJjPji9hZG7/bE6dkQhAQ9ZuRIhY3zB5/+z21/dnGUg5M9hQ0gPNHI4cz5kgo6aNeTHYQoXwpa32iABBdpK5570QG5W2Uf03pF/BMokCqpCwJmOz2DFk46Niep87qgsVVQQrCiG2PsYa0zUvz8eZKU5x47Y6AfpvjMb3XVqoKjoagcZH5BN6/8itJvoA6k8Ho9fwFCwiLZ5gVNEN+HO5rn6Fh1JZyto5aBczGlH/A+Wyh6s+NFG3PdD5l4tA/uW8EIPnhgNx//tRPp87YlNejt/In+pkxJqKJV+kaUh8Eet2nvnjdclU1aX4V9TaAkEUG/baChslWLmbvKaR5R/jwB8IKWdfDrQtpu1cFczobdlZsDUlRjLrd25mw/P8Ks7p/vkipxt+u7KcoD351fnQF5YcRwlDtD1l8YFYdikX5e4vYnGvMsIAXPFFM0FK95nuAdb7pTQYhdxew2x07AJLk/djh93zkY8JslVwd3UxBkhY2xqCO0qmtDecAQQV3r9zWno0+xw==
    SecretAccessKey: AgBgkQKxQBvrXClayc1femgdnwF/gEE8XmLWCyu4XldTMw0DwmjfXgttjtViDGDh3GR5MONsD6ehtLFuJfW7budZYAX0bgHC0gn38nEusTOUT41CPuh3ISj5oLk20msL8zUH/n2ShtkJ6McpTKFNNjyKSNv9Cj352WA4z97LN/LlDbObYkK+D0L1dWVLP6eRbnn/JzyvMB/t/O44kZPwROz7JCLmbOZTw5a8nCw2b/IFkAHVESZELFi71yA21sunJNHNhPwHdW6UrFSFOHoSaUo7Zc3Vp+2MCYfQhZ3uvSZ1D/Y9YyPQCQoUXZJhWXQgCEw+Mx1vrBhMHXDk1oRM9hyxAsE3qbfRsnuBkVMTGignryTCdAv+RhZjL0Ae4Uiyo/lUVYrhDjpnCdn5Mc8l39C06DOFTmWc9ujh6t8uVIP8zY2N/vAnBmKPU658OoVpX57vdId8ogVV5orj8TEQQOliOEjeyFfu0X5Nzwb3ttAccM5qFyV7lhTiST62GGOslRwNkkFw7uat7OSg1NJ2QazWuzT5gnQEeP7vknVEC4vEyW02svWX971uvuvWG1qnRIqRr8vo3I1Q88fjrzPtFmmIiWi/3PGj22CQfZaGiUayNW3l9sYu08ODjLrTzq0eGOlOXpR5E9oDAR4Y0kHkm9lm0pmclePSLP6yOrtL7RZl/iwN3EN9101RI5onBZKayJG5AjnQ5S8UDncCFrq396j2FTztYcS2t/8CSbIm6BxYA+2OZ2feqr8t
  template:
    metadata:
      creationTimestamp: null
      name: aws-cluster-identity-secret
      namespace: hmc-system
