---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-cluster-identity-secret
  namespace: hmc-system
spec:
  encryptedData:
    AccessKeyID: AgC42RzSLeDrSvaR4TMY55/Y8M5ti+viCH70rto1ADnCJSYkWuWz6NPNZ3Y5vf6BRZtrChRWiv3NN9YfcIciL2/f/whVuQRxqimQ6yJIx7/moXyjjhxIKWQ1oSn3+byWHgV1t1huSM5VpIRv732cK0XycZt2pWbGwlg7bO+LVnndZ3+w++4tECPClMMTQX6MsdPiAuqCcyBn82BGyLPXG+SHXm9pTDu+nT55XUH9CIi1wITuCrRcc+aTw2yyTkVNNjC6iGbtSHTZvCxGZU113bnY9hys4K9hpHpAQE1LCQOsaSXgTreI2HTbb+LTx4GBHC57mmDVL66b00xsm5ctMO7hN+4kO+Sg2tCZA4HQ9Bn5pToAe68j2fUHpvJyFlWVgUBKk2t0fvqHrJBKtrErdH66u/8lfr31/8IUmebUm+TQqkdbHCTGjGFGewxr6Nvjs+VgvXhB6mY9vCOVNOtwIjDFsMURjD4zi6TzQXlg7JQSLi9UytSCniXIVZu0mkquBIpaFQLXu6MfANh7ZwtF0iq9sYiHLcCTEUOiVMK/xqn+GX4dwnXZNr6eS4sd9peqv2kB24LxcLWC6XUB/8ztdgZJNbZr8EMimfjFcf2qghpDuAgoUvngh94f4lpZ+/dXDZWAqiEDZFVvx/Tdw6xnr1F02JPrFXZL3+WayzSqrJU3AEj2xRvTj/gQWfSV6r2oR2AFAbWAsIxmTCvwntWbuS6x1i/7/A==
    SecretAccessKey: AgBTd2XI2QUBBi04R34NV9RmdDYy58aJdduCqa+H9ZEkn+zOCKf8IrZhexL+u2sqUXt2yyoF0Nd9Ytv51FoxXomuupP1bbrx9A0tUyg4Q3cpVWSI285yTJTxfmjclxc2q2aYJHlyD8JsHuLSadfT+kteqB5cuUw5Ws8UPxsN3jqOKGVdt8cqKcwjiWKEpB2qQGOaQUNuTupvB6845+RaEeg4rd/L4EloIdZx9G9r2kUlEcb5LV2uzgurjaMUWz1ftKYs2RfdsfdPbhZ2uda7CvFkNkvdTtJROkHB9WSU+MBy3CccMU8YNoqRVaIjYrcUmOma2mJtEeQeAlU/DFwOMPAY92mT25fChpo06QFEhfUjW7waXfR4PaaL20PnhxcnL0l+oCI+aSx8UQOR63SEK56zsTkN17qO7wBqLzpr4AIjo2WIFyeYGI4il4cBapQIn9p2zjKQQc83LBnjokH0bGgGXe6cIMOs3QgYfgg2kg0e1/WZJesZEY9tBlqCx0TPzoXpJWIDTAy5l3BHwx7kz2YIQoNYs+C04aN19gR41W0nJbeAuIqDXhGPIAz1IDFnmeIR8jNT3hKbQ+1dk45/5YRqrV//dPQ8436aTAgRrUbK828zY5uDtlbsHRFFfBli8UF9++mEarUKJmiwfNKwAThqKV/3SXVr5rL/19axHn06Npf+UusBowxO+oQUQ7PQn+Bsw1ZMUeiNCOD8r0OWeVA+9uKeDuS7LySIvZTsZqUGhcghBmMw3WTI
  template:
    metadata:
      creationTimestamp: null
      name: aws-cluster-identity-secret
      namespace: hmc-system
