---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-cluster-identity-secret
  namespace: hmc-system
spec:
  encryptedData:
    AccessKeyID: AgA18zy+YpYvPf/fBZAfrvagcTvY3DYWDqLVBFJUXF9zUKZ5B2uG1SsbAMNIzEW5OOecXXxUjLTJyi6m9h5pQyaUrfYSmdYcnERF9G6AVXRGpb2tFUkConjNuBLSb1ZPs1o2ERtPkRsbH/+a13PYPTCzi2ooyQYScsuhoD87UkCs3JNZf+3SIANRmyjWo3ClOHT0jNpVOZXlxuzzgzC9fszY/DEFRw68yXkZqOeKPO7airS7YUCirQnDQwc1dMAsfq81Bw7JZrjF+3hdox/D8SvGe3Zl0gZ5ja9Bt13REPpjtmWygUblHirzCjyL8t07uTUo9xNwtP0hRgS6S+U5tq9Ep5GPv/jfGy8Xg9UnD3WjnMUR4Dha0e2i/Gj75r7Lcuqa3H09FdEnwC9tgxHkx4MvXIOvVJ/VZRUpFVM6UPoGCrdHVf80hjAtOP6YtcOFZfRhMOWKYvFJwRMODvDmnMXwJzzUVeC/yMrY9SgwbRb1qN+f742tbqUPfYjGulnykX1E3acpo96nXFU4BN7pq2gYwLTdYQgojg9ohstJOyfz3tnbrCDHiTNOXNQ3ebZPmmMNOV0RIcm1KvTPMX2elM0mdM/E29p9vrtZinmmPH1x5N+72FdZxeGH4KWl3/D7TYvLAxiaFocemZF/qAQqO9bH842Hm1L2kCvgjzp2gRWA5j60HQqI4QrztJDGVMGjLapsmjajsYXergRGP+R1nD3RAhTvNQ==
    SecretAccessKey: AgAdV2nLKYrVQS1wqV0RyGDoKzidiQZLilADQwgMCDbIcgcG7+a0DXB4P2usLD5vPBbizT+t6K4SUU2rP5fee+EFV5+KcuLEWXRcVybqU1obEFxzQHqoRdIlfVvR6sQrtdriqFCJNhmKlmPQ1IkXFRaSbdk9qoY0h3bl6SFyHw4O9SjbkTgoIZWIGQxJXeeSOxrXrPBj5jtyfuR4qSvvbKFY9AObTMbraeL1If5YF3hb2ZuJsV4aHXEJ7kmKs/icsezQTJN1lXbfNHK7N+vO5rcVgDyazV7yHGVhN7lSIJhq9dWptxtGRU5DUt6oVVIm77Is7En4qMWkF9QbxiAe7Xo/Xhw/mhA3QTE8UlTbyaaz2yHS813M3hdJzLYQf/0TLyF76lH/FEpeu2Y7TNFftokPRAPEn7rh86CQLa95Jf+RwcPQ5s8zLDO55PjUF5o9kxRgxV8sN/SYfjwLyXUXZIFe1TZd6QSLNdFrvQBZFSopuh+RWGvVBgi1pjKOXdcHhrauSVizt1STcbxd0QnJac1VwlaT9hz7aGs4j122vIcSsjQ2Em4WrVKseZrrQ1qbXaZ/hYF4Kcnf7x/VyLWzPbK7qhbEgUYcdRoxmRghQL0D06IkJtgI52RzFZfvlcLs79C1wIP1vfD34dqVG9yflR0lOTYMt3yVxOqyW20BtKLSJP6KQR9G/EhV2fXpgI8jdJ9WxclDpnRmg5E7xoz3VuSEu2557Qm+B4rSad0zb0kO8Tz87I7O8YEP
  template:
    metadata:
      creationTimestamp: null
      name: aws-cluster-identity-secret
      namespace: hmc-system
